"""Add role column to User model

Revision ID: 606555566f25
Revises: 
Create Date: 2024-12-05 15:57:23.692965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '606555566f25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
